### PR TITLE
Fix bot

### PR DESCRIPTION
**Pull request by DaveH355**
I added a bot for the capture the flag gamemode on Gimkit. It runs with the help of the ClickIsTrusted extension. All credit for the extension to [orstavik](https://github.com/orstavik/ClickIsTrusted)

Gimkit randomly changes the id of all their HTML elements so it's hard to directly read the text values. But since all the elements are still in the same place, you can read them through an array
Chrome extensions can generate trusted mouse and keyboard events, so the bot passes its events to the ClickIsTrusted extension
And that's how the bot works. My code is really bad,  if you want you can just implement the fixes and not actually merge the code

Anyway, To run the bot:
 install the extension
 run the script in the console
 click on the extension to activate it. Press p to start and o to stop. 

**Known Issues**
The bot may try to answer questions too fast and crash
The extension will probably deactivate after you press o to stop the bot. Just activate it again before pressing p to start again

### CODE REVIEW

**Comment by ecc521** [comment]
@TreeBronch 
Pinging you to make sure you see this PR. I've been busy, so haven't gotten to testing it.

**Comment by DaveH355** [comment]
I changed the script to work with almost all game modes. Optionally, it runs in the Tampermonkey extension, which will store all the guessed answers for future use. 

The basics are the same, run the script in the chrome console and activate the Click-Is-Trusted extension

Main Controls are: 
P - start answering
O - stop answering
U - toggle safe mode

Code quality was decreased :)

**Comment by DaveH355** [comment]
Gimkit added a 3 second cooldown if you get a question wrong. This makes brute forcing questions kind of pointless. I'll wait until after the school year starts to see what new changes they're going to add. Then I'll patch the script. 

Script still works, just not very powerful

**Comment by ecc521** [comment]
Not surprising. 
There is (or at least was) a literal website hack to get the website answers, but I haven't tested it. 

And legally it's a lot more questionable

**Pull request merged**
